services:
  app:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 3000:3000
  db:
    image: postgres:13.22-trixie
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - data_sql:/var/lib/postgresql/data   # Persistent data storage
      - ./seed.sql:/docker-entrypoint-initdb.d/seed.sql  # Run this on init
    ports:
      - 5432:5432

volumes:
  data_sql: