[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "xxx"

[auth.google]
client_id = "xxx.apps.googleusercontent.com"
client_secret = "xxx"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"